#!/bin/bash -e

cd ..
mkdir -p build
cd build
rm -rf *
cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_DOCS=OFF -DBUILD_PACKAGE=OFF -DBUILD_PERF_TESTS=OFF -DBUILD_TESTS=OFF -DBUILD_WITH_DEBUG_INFO=OFF -DBUILD_opencv_apps=OFF \
-DBUILD_opencv_calib3d=OFF -DBUILD_opencv_features2d=OFF -DBUILD_opencv_flann=OFF -DBUILD_opencv_highgui=OFF -DBUILD_opencv_imgcodecs=ON \
-DBUILD_opencv_objdetect=OFF -DBUILD_opencv_photo=OFF -DBUILD_opencv_python2=OFF -DBUILD_opencv_shape=OFF -DBUILD_opencv_stitching=OFF -DBUILD_opencv_superres=OFF \
-DBUILD_opencv_ts=OFF -DBUILD_opencv_videoio=OFF -DBUILD_opencv_videostab=OFF -DCPACK_BINARY_DEB=ON -DCPACK_BINARY_STGZ=OFF \
-DCPACK_BINARY_TGZ=OFF -DCPACK_BINARY_TZ=OFF -DWITH_CUDA=OFF -DOPENCV_DOWNSTREAM_VERSION=${BAMBOO_BUILDNUMBER} -DWITH_LAPACK=OFF
make
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/lib
make package
OPENCV_VERSION=$(git describe --tags --abbrev=0)
mv OpenCV_${OPENCV_VERSION}-${BAMBOO_BUILDNUMBER}_amd64-dev.deb OpenCV-dev_${OPENCV_VERSION}-${BAMBOO_BUILDNUMBER}_amd64.deb
mv OpenCV_${OPENCV_VERSION}-${BAMBOO_BUILDNUMBER}_amd64-libs.deb OpenCV-libs_${OPENCV_VERSION}-${BAMBOO_BUILDNUMBER}_amd64.deb

