#!/bin/bash -e

cd ..
mkdir -p build-debug
cd build-debug
rm -rf *
cmake .. -DCMAKE_BUILD_TYPE=Debug -DBUILD_DOCS=OFF -DBUILD_PACKAGE=OFF -DBUILD_PERF_TESTS=OFF -DBUILD_TESTS=OFF -DBUILD_WITH_DEBUG_INFO=ON -DBUILD_opencv_apps=OFF \
-DBUILD_opencv_calib3d=OFF -DBUILD_opencv_features2d=OFF -DBUILD_opencv_flann=OFF -DBUILD_opencv_highgui=ON -DBUILD_opencv_imgcodecs=ON \
-DBUILD_opencv_objdetect=ON -DBUILD_opencv_photo=OFF -DBUILD_opencv_python2=OFF -DBUILD_opencv_shape=OFF -DBUILD_opencv_stitching=OFF -DBUILD_opencv_superres=OFF \
-DBUILD_opencv_ts=OFF -DBUILD_opencv_videoio=ON -DBUILD_opencv_videostab=OFF -DCPACK_BINARY_DEB=ON -DCPACK_BINARY_STGZ=OFF \
-DCPACK_BINARY_TGZ=OFF -DCPACK_BINARY_TZ=OFF -DWITH_CUDA=OFF -DOPENCV_DOWNSTREAM_VERSION=${BAMBOO_BUILDNUMBER} -DWITH_LAPACK=OFF -DENABLE_PRECOMPILED_HEADERS=OFF -DBUILD_opencv_java=OFF
make
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/lib
make package

